package com.ghkdtlwns987.apiserver.Member.Exception;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {

    MEMBER_ALREADY_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER IS ALREADY EXISTS"),
    MEMBER_PHONE_ALREADY_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER PHONE ALREADY EXISTS"),
    MEMBER_EMAIL_ALREADY_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER EMAIL ALREADY EXISTS"),
    MEMBER_NICKNAME_ALREADY_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER NICKNAME ALREADY EXISTS"),
    MEMBER_ALREADY_WITHDRAW("M001", HttpStatus.BAD_REQUEST, "MEMBER ALREADY WITHDRAW"),
    MEMBER_LOGINID_ALREADY_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER LOGINID ALREADY EXUSTS"),

    MEMBER_NOT_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER NOT EXISTS"),
    MEMBER_NICKNAME_NOT_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER NICKNAME NOT EXISTS"),
    MEMBER_EMAIL_NOT_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER EMAIL NOT EXISTS"),
    MEMBER_LOGINID_NOT_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER LOGIN_ID NOT EXISTS"),
    MEMBER_PHONE_NOT_EXISTS("M001", HttpStatus.BAD_REQUEST, "MEMBER_PHONE_NOT_EXISTS"),
    INVALID_TYPE_VALUE("C004", HttpStatus.BAD_REQUEST, "INVALID TYPE VALUE"),

    INVALID_PASSWORD_INPUT("I001", HttpStatus.INTERNAL_SERVER_ERROR, "INVALID PASSWORD TYPE"),

    ORDER_ID_ALREADY_EXISTS("O001", HttpStatus.INTERNAL_SERVER_ERROR, "ORDER ID IS ALREADY EXISTS"),
    PRODUCT_ID_ALREADY_EXISTS("O002", HttpStatus.INTERNAL_SERVER_ERROR, "PRODUCT ID IS ALREADY EXISTS"),
    PRODUCT_ID_NOT_EXISTS("O002", HttpStatus.INTERNAL_SERVER_ERROR, "PRODUCT ID IS NOT EXISTS"),
    ;

    private final String code;
    private final HttpStatus status;
    private final String message;
}
