SERVER_PORT : 8000
AUTHENTICATION: http://localhost:8000/authentication
AUTHORIZATION: http://localhost:8000/authorization
ORDER: http://localhost:8002/api/v1
CATALOG: http://localhost:8001/api/v1
server:
  port: ${SERVER_PORT}

spring:
  profiles:
    active:
      on-profile:
        - prod
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  # JPA
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.MariaDB103Dialect
    format_sql: true
    show-sql: true
    defer-datasource-initialization: true


  datasource:
    url: jdbc:mariadb://117.16.17.165:13000/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

auth:
  authentication:
    url: ${AUTHENTICATION}
  authorization:
    url: ${AUTHORIZATION}

order:
  url: ${ORDER}
catalog:
  url: ${CATALOG}